CREATE TABLE IF NOT EXISTS role_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    requested_role ENUM('realtor', 'admin', 'super_admin') NOT NULL,
    user_current_role ENUM('user', 'realtor', 'admin', 'super_admin') NOT NULL,
    reason TEXT NOT NULL,
    company_name VARCHAR(255),
    company_address TEXT,
    tax_number VARCHAR(50),
    phone VARCHAR(20),
    experience_years INT DEFAULT 0,
    license_number VARCHAR(100),
    documents JSON,
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    admin_notes TEXT,
    reviewed_by INT,
    reviewed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_requested_role (requested_role),
    INDEX idx_created_at (created_at)
); 