-- Seçili İllerin Tüm İlçeleri
-- Antalya, İzmir, İstanbul, Ankara, Tekirdağ, Edirne, Kırklareli
-- MySQL 5.7+ Compatible Version

-- Disable foreign key checks temporarily
SET FOREIGN_KEY_CHECKS = 0;

-- Insert Districts Data for Selected Cities
INSERT INTO districts (city_id, name, created_at, updated_at) VALUES

-- İSTANBUL İLÇELERİ (ID: 34) - 39 İlçe
(34, 'Adalar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Arnavutköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Ataşehir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Avcılar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Bağcılar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Bahçelievler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Bakırköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Başakşehir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Bayrampaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Beşiktaş', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Beykoz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Beylikdüzü', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Beyoğlu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Büyükçekmece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Çatalca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Çekmeköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Esenler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Esenyurt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Eyüpsultan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Fatih', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Gaziosmanpaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Güngören', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Kadıköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Kağıthane', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Kartal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Küçükçekmece', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Maltepe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Pendik', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Sancaktepe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Sarıyer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Silivri', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Sultanbeyli', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Sultangazi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Şile', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Şişli', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Tuzla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Ümraniye', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Üsküdar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Zeytinburnu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- ANKARA İLÇELERİ (ID: 6) - 25 İlçe
(6, 'Akyurt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Altındağ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Ayaş', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Bala', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Beypazarı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Çamlıdere', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Çankaya', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Çubuk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Elmadağ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Etimesgut', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Evren', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Gölbaşı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Güdül', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Haymana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Kahramankazan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Kalecik', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Keçiören', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Kızılcahamam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Mamak', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Nallıhan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Polatlı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Pursaklar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Sincan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Şereflikoçhisar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Yenimahalle', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- İZMİR İLÇELERİ (ID: 35) - 30 İlçe
(35, 'Aliağa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Balçova', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Bayındır', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Bayraklı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Bergama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Beydağ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Bornova', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Buca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Çeşme', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Çiğli', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Dikili', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Foça', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Gaziemir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Güzelbahçe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Karabağlar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Karaburun', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Karşıyaka', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Kemalpaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Kınık', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Kiraz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Konak', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Menderes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Menemen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Narlıdere', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Ödemiş', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Seferihisar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Selçuk', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Tire', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Torbalı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Urla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- ANTALYA İLÇELERİ (ID: 7) - 19 İlçe
(7, 'Aksu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Alanya', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Demre', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Döşemealtı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Elmalı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Finike', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Gazipaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Gündoğmuş', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'İbradı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Kaş', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Kemer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Kepez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Konyaaltı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Korkuteli', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Kumluca', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Manavgat', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Muratpaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Serik', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Akseki', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- TEKİRDAĞ İLÇELERİ (ID: 59) - 11 İlçe
(59, 'Çerkezköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Çorlu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Ergene', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Hayrabolu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Kapaklı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Malkara', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Marmaraereğlisi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Muratlı', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Saray', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Süleymanpaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Şarköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- EDİRNE İLÇELERİ (ID: 22) - 9 İlçe
(22, 'Enez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Havsa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'İpsala', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Keşan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Lalapaşa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Meriç', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Merkez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Süloğlu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Uzunköprü', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- KIRKLARELI İLÇELERİ (ID: 39) - 8 İlçe
(39, 'Babaeski', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Demirköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Kofçaz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Lüleburgaz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Merkez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Pehlivanköy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Pınarhisar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Vize', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)

ON DUPLICATE KEY UPDATE 
name = VALUES(name),
updated_at = CURRENT_TIMESTAMP;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Show summary for selected cities
SELECT 
    c.name as city_name,
    c.plate_code,
    COUNT(d.id) as district_count
FROM cities c
LEFT JOIN districts d ON c.id = d.city_id
WHERE c.id IN (34, 6, 35, 7, 59, 22, 39)
GROUP BY c.id, c.name, c.plate_code
ORDER BY c.plate_code;